--EHITRANS
---------------------------------------------------------------------------------Setting up the data in STG_IPAAS_CLAIM table

INSERT INTO STG_IPAAS_CLAIM
(REC_ID, CLIENT_ID, CLIENT_SUB_ID, FILE_SUBMIT_GRP_ID, CLAIM_NBR, CLAIM_ADJ_CD, ADJ_FROM_CLAIM_NBR, 
CLAIM_STS_CD, SYS_SUBSC_ID, SYS_MBR_ID, CLIENT_HIERARCHY_LVL1, CLIENT_HIERARCHY_LVL2, 
CLIENT_HIERARCHY_LVL3, 
CLIENT_HIERARCHY_LVL4, 
MBR_PCP_NBR, PROV_ID, PAYEE_ID, PAYEE_TIN, APPROVE_DAY_AMT, ACTUAL_DAY_AMT, RECEIVE_DT, PAY_DT, DRG_CD, SUBMIT_DRG_CD, BILL_CLASS_CD, FACILITY_TP_CD,
HOSP_FREQ_CD, ADMIT_SRC_CD, ADMIT_TP_CD, HOSP_ADMIT_DT, HOSP_ADMIT_HR, HOSP_DISCHARGE_DT, HOSP_DISCHARGE_HR, HOSP_DISCHARGE_STS_CD, ATTENDING_PROV_ID,
PROV_ADDR_CD, OOA_IND, EDI_REF_ID, CLIENT_SPECIFIC_TXT1, CLIENT_SPECIFIC_TXT2, CLIENT_SPECIFIC_TXT3, CLIENT_SPECIFIC_TXT4, CLIENT_SPECIFIC_TXT5, 
CLIENT_SPECIFIC_TXT6, CLIENT_SPECIFIC_TXT7, CLIENT_SPECIFIC_TXT8, CLIENT_SPECIFIC_TXT9, CLIENT_SPECIFIC_TXT10, REC_DEL_IND, DRG_CODE_TP_CD, SUBMIT_DRG_CODE_TP_CD)
SELECT TOP 100 REC_ID, CLIENT_ID, CLIENT_SUB_ID, FILE_SUBMIT_GRP_ID, CLAIM_NBR, CLAIM_ADJ_CD, ADJ_FROM_CLAIM_NBR, 
CLAIM_STS_CD, SYS_SUBSC_ID, SYS_MBR_ID, CLIENT_HIERARCHY_LVL1, CLIENT_HIERARCHY_LVL2, 
CLIENT_HIERARCHY_LVL3, 
CLIENT_HIERARCHY_LVL4, 
MBR_PCP_NBR, PROV_ID, PAYEE_ID, PAYEE_TIN, APPROVE_DAY_AMT, ACTUAL_DAY_AMT, RECEIVE_DT, PAY_DT, DRG_CD, SUBMIT_DRG_CD, BILL_CLASS_CD, FACILITY_TP_CD,
HOSP_FREQ_CD, ADMIT_SRC_CD, ADMIT_TP_CD, HOSP_ADMIT_DT, HOSP_ADMIT_HR, HOSP_DISCHARGE_DT, HOSP_DISCHARGE_HR, HOSP_DISCHARGE_STS_CD, ATTENDING_PROV_ID,
PROV_ADDR_CD, OOA_IND, EDI_REF_ID, CLIENT_SPECIFIC_TXT1, CLIENT_SPECIFIC_TXT2, CLIENT_SPECIFIC_TXT3, CLIENT_SPECIFIC_TXT4, CLIENT_SPECIFIC_TXT5, 
CLIENT_SPECIFIC_TXT6, CLIENT_SPECIFIC_TXT7, CLIENT_SPECIFIC_TXT8, CLIENT_SPECIFIC_TXT9, CLIENT_SPECIFIC_TXT10, REC_DEL_IND, DRG_CODE_TP_CD, SUBMIT_DRG_CODE_TP_CD

FROM STG_CLAIM



UPDATE STG_IPAAS_CLAIM
SET CLAIM_ADJ_CD = NULL

UPDATE STG_IPAAS_CLAIM
SET CLAIM_ADJ_CD = ''
WHERE FILE_SUBMIT_GRP_ID = '0000000936'


---------------------------------------------------------------------------------------------------



